displayName=Group Ironman Tracker
author=Danj
description=Syncs Group Ironman activity across group members
tags=GIM, Group Ironman, Tracker, Group, Ironman
plugins=com.dan.gimtracker.GIMTrackerPlugin
